CREATE PROCEDURE [COR].[DeleteUser]
@ExecID UNIQUEIDENTIFIER, @ID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION;

DELETE [COR].[UserPermissions]
WHERE  FK_User_ID = @ID;

DELETE [COR].[Users]
WHERE  PK_ID = @ID;

COMMIT TRANSACTION;