import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ToggleSwitchModule } from 'primeng/toggleswitch';
import { ButtonModule } from 'primeng/button';
import { PopoverModule } from 'primeng/popover';
import { FloatTextInput } from './floattextinput';
import { Divider } from 'primeng/divider';

@Component({
    selector: 'app-floaticonselector',
    imports: [FormsModule, CommonModule, ButtonModule, PopoverModule, FloatTextInput, Divider],
    template: `
        @if (!hidden) {
            <p-button (click)="op.toggle($event)" text icon="pi {{ value }}" [disabled]="disabled" />
            <p-popover #op>
                <div>
                    <app-floattextinput #sch icon="pi-search" label="Search" (valueChange)="doSearch(sch.value)" />
                    <p-divider />
                    @if (currentIcons.length > 0) {
                        <div class="flex flex-wrap w-[25vw]" style="max-height:30vh;overflow-y:auto">
                            @for (icon of currentIcons; track icon) {
                                <p-button icon="pi {{ icon }}" text (click)="setIcon(icon); op.hide()" />
                            }
                        </div>
                    } @else {
                        <p>No icons match your search!</p>
                    }
                </div>
            </p-popover>
        }
    `
})
export class FloatIconSelector implements OnChanges {
    @Input() disabled: boolean = false;
    @Input() hidden: boolean = false;

    @Input() value: string | undefined = undefined;
    @Output() valueChange = new EventEmitter<string | undefined>();

    constructor() {
        this.currentIcons = [...this.icons];
    }

    icons: string[] = [
        'pi-address-book',
        'pi-align-center',
        'pi-align-justify',
        'pi-align-left',
        'pi-align-right',
        'pi-amazon',
        'pi-android',
        'pi-angle-double-down',
        'pi-angle-double-left',
        'pi-angle-double-right',
        'pi-angle-double-up',
        'pi-angle-down',
        'pi-angle-left',
        'pi-angle-right',
        'pi-angle-up',
        'pi-apple',
        'pi-arrow-circle-down',
        'pi-arrow-circle-left',
        'pi-arrow-circle-right',
        'pi-arrow-circle-up',
        'pi-arrow-down',
        'pi-arrow-down-left',
        'pi-arrow-down-left-and-arrow-up-right-to-center',
        'pi-arrow-down-right',
        'pi-arrow-left',
        'pi-arrow-right',
        'pi-arrow-right-arrow-left',
        'pi-arrow-up',
        'pi-arrow-up-left',
        'pi-arrow-up-right',
        'pi-arrow-up-right-and-arrow-down-left-from-center',
        'pi-arrows-alt',
        'pi-arrows-h',
        'pi-arrows-v',
        'pi-asterisk',
        'pi-at',
        'pi-backward',
        'pi-ban',
        'pi-barcode',
        'pi-bars',
        'pi-bell',
        'pi-bell-slash',
        'pi-bitcoin',
        'pi-bolt',
        'pi-book',
        'pi-bookmark',
        'pi-bookmark-fill',
        'pi-box',
        'pi-briefcase',
        'pi-building',
        'pi-building-columns',
        'pi-bullseye',
        'pi-calculator',
        'pi-calendar',
        'pi-calendar-clock',
        'pi-calendar-minus',
        'pi-calendar-plus',
        'pi-calendar-times',
        'pi-camera',
        'pi-car',
        'pi-caret-down',
        'pi-caret-left',
        'pi-caret-right',
        'pi-caret-up',
        'pi-cart-arrow-down',
        'pi-cart-minus',
        'pi-cart-plus',
        'pi-chart-bar',
        'pi-chart-line',
        'pi-chart-pie',
        'pi-chart-scatter',
        'pi-check',
        'pi-check-circle',
        'pi-check-square',
        'pi-chevron-circle-down',
        'pi-chevron-circle-left',
        'pi-chevron-circle-right',
        'pi-chevron-circle-up',
        'pi-chevron-down',
        'pi-chevron-left',
        'pi-chevron-right',
        'pi-chevron-up',
        'pi-circle',
        'pi-circle-fill',
        'pi-circle-off',
        'pi-circle-on',
        'pi-clipboard',
        'pi-clock',
        'pi-clone',
        'pi-cloud',
        'pi-cloud-download',
        'pi-cloud-upload',
        'pi-code',
        'pi-cog',
        'pi-comment',
        'pi-comments',
        'pi-compass',
        'pi-copy',
        'pi-credit-card',
        'pi-crown',
        'pi-database',
        'pi-delete-left',
        'pi-desktop',
        'pi-directions',
        'pi-directions-alt',
        'pi-discord',
        'pi-dollar',
        'pi-download',
        'pi-eject',
        'pi-ellipsis-h',
        'pi-ellipsis-v',
        'pi-envelope',
        'pi-equals',
        'pi-eraser',
        'pi-ethereum',
        'pi-euro',
        'pi-exclamation-circle',
        'pi-exclamation-triangle',
        'pi-expand',
        'pi-external-link',
        'pi-eye',
        'pi-eye-slash',
        'pi-face-smile',
        'pi-facebook',
        'pi-fast-backward',
        'pi-fast-forward',
        'pi-file',
        'pi-file-arrow-up',
        'pi-file-check',
        'pi-file-edit',
        'pi-file-excel',
        'pi-file-export',
        'pi-file-import',
        'pi-file-o',
        'pi-file-pdf',
        'pi-file-plus',
        'pi-file-word',
        'pi-filter',
        'pi-filter-fill',
        'pi-filter-slash',
        'pi-flag',
        'pi-flag-fill',
        'pi-folder',
        'pi-folder-open',
        'pi-folder-plus',
        'pi-forward',
        'pi-gauge',
        'pi-gift',
        'pi-github',
        'pi-globe',
        'pi-google',
        'pi-graduation-cap',
        'pi-hammer',
        'pi-hashtag',
        'pi-headphones',
        'pi-heart',
        'pi-heart-fill',
        'pi-history',
        'pi-home',
        'pi-hourglass',
        'pi-id-card',
        'pi-image',
        'pi-images',
        'pi-inbox',
        'pi-indian-rupee',
        'pi-info',
        'pi-info-circle',
        'pi-instagram',
        'pi-key',
        'pi-language',
        'pi-lightbulb',
        'pi-link',
        'pi-linkedin',
        'pi-list',
        'pi-list-check',
        'pi-lock',
        'pi-lock-open',
        'pi-map',
        'pi-map-marker',
        'pi-mars',
        'pi-megaphone',
        'pi-microchip',
        'pi-microchip-ai',
        'pi-microphone',
        'pi-microsoft',
        'pi-minus',
        'pi-minus-circle',
        'pi-mobile',
        'pi-money-bill',
        'pi-moon',
        'pi-objects-column',
        'pi-palette',
        'pi-paperclip',
        'pi-pause',
        'pi-pause-circle',
        'pi-paypal',
        'pi-pen-to-square',
        'pi-pencil',
        'pi-percentage',
        'pi-phone',
        'pi-pinterest',
        'pi-play',
        'pi-play-circle',
        'pi-plus',
        'pi-plus-circle',
        'pi-pound',
        'pi-power-off',
        'pi-prime',
        'pi-print',
        'pi-qrcode',
        'pi-question',
        'pi-question-circle',
        'pi-receipt',
        'pi-reddit',
        'pi-refresh',
        'pi-replay',
        'pi-reply',
        'pi-save',
        'pi-search',
        'pi-search-minus',
        'pi-search-plus',
        'pi-send',
        'pi-server',
        'pi-share-alt',
        'pi-shield',
        'pi-shop',
        'pi-shopping-bag',
        'pi-shopping-cart',
        'pi-sign-in',
        'pi-sign-out',
        'pi-sitemap',
        'pi-slack',
        'pi-sliders-h',
        'pi-sliders-v',
        'pi-sort',
        'pi-sort-alpha-down',
        'pi-sort-alpha-down-alt',
        'pi-sort-alpha-up',
        'pi-sort-alpha-up-alt',
        'pi-sort-alt',
        'pi-sort-alt-slash',
        'pi-sort-amount-down',
        'pi-sort-amount-down-alt',
        'pi-sort-amount-up',
        'pi-sort-amount-up-alt',
        'pi-sort-down',
        'pi-sort-down-fill',
        'pi-sort-numeric-down',
        'pi-sort-numeric-down-alt',
        'pi-sort-numeric-up',
        'pi-sort-numeric-up-alt',
        'pi-sort-up',
        'pi-sort-up-fill',
        'pi-sparkles',
        'pi-spinner',
        'pi-spinner-dotted',
        'pi-star',
        'pi-star-fill',
        'pi-star-half',
        'pi-star-half-fill',
        'pi-step-backward',
        'pi-step-backward-alt',
        'pi-step-forward',
        'pi-step-forward-alt',
        'pi-stop',
        'pi-stop-circle',
        'pi-stopwatch',
        'pi-sun',
        'pi-sync',
        'pi-table',
        'pi-tablet',
        'pi-tag',
        'pi-tags',
        'pi-telegram',
        'pi-th-large',
        'pi-thumbs-down',
        'pi-thumbs-down-fill',
        'pi-thumbs-up',
        'pi-thumbs-up-fill',
        'pi-thumbtack',
        'pi-ticket',
        'pi-tiktok',
        'pi-times',
        'pi-times-circle',
        'pi-trash',
        'pi-trophy',
        'pi-truck',
        'pi-turkish-lira',
        'pi-twitch',
        'pi-twitter',
        'pi-undo',
        'pi-unlock',
        'pi-upload',
        'pi-user',
        'pi-user-edit',
        'pi-user-minus',
        'pi-user-plus',
        'pi-users',
        'pi-venus',
        'pi-verified',
        'pi-video',
        'pi-vimeo',
        'pi-volume-down',
        'pi-volume-off',
        'pi-volume-up',
        'pi-wallet',
        'pi-warehouse',
        'pi-wave-pulse',
        'pi-whatsapp',
        'pi-wifi',
        'pi-window-maximize',
        'pi-window-minimize',
        'pi-wrench',
        'pi-youtube'
    ];

    currentIcons: string[] = [];

    ngOnChanges(changes: SimpleChanges) {
        if (changes['value'] && changes['value'].currentValue != changes['value'].previousValue) {
            this.value = changes['value'].currentValue;
        }
    }

    setIcon(value: string) {
        this.value = value;
        this.valueChange.emit(this.value);
    }

    doSearch(text: string | null | undefined) {
        if (text) this.currentIcons = [...this.icons.filter((x) => x.indexOf(text) != -1)];
        else this.currentIcons = [...this.icons];
    }
}
