CREATE PROCEDURE [COR].[UpdatePassword]
@ExecID UNIQUEIDENTIFIER, @NewPassword NVARCHAR (MAX)
AS
BEGIN TRANSACTION;

UPDATE  [COR].[Users]
    SET LoginPassword = @NewPassword
WHERE   PK_ID = @ExecID;

COMMIT TRANSACTION;