CREATE PROCEDURE [COR].[SP_DeleteUser]
	@ExecID UNIQUEIDENTIFIER,
	@ID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION
	DELETE FROM [COR].[UserPermissions] WHERE FK_User_ID = @ID;
	DELETE FROM [COR].[Users] WHERE PK_ID = @ID;
COMMIT