CREATE PROCEDURE [COR].[SP_GetUser]
	@ExecID UNIQUEIDENTIFIER,
	@ID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION
	SELECT * FROM [COR].[Users] WHERE PK_ID = @ID
	SELECT * FROM [COR].[UserPermissions] WHERE FK_User_ID = @ID
COMMIT